-- -------------------------------------------------------------
-- 
-- File Name: /home/sky/Documents/MATLAB/Low_density_parity_code/archive/codegen/call_custom_exp/hdlsrc/call_custom_exp_fixpt.vhd
-- Created: 2019-04-07 16:50:30
-- 
-- Generated by MATLAB 9.5, MATLAB Coder 4.1 and HDL Coder 3.13
-- 
-- 
-- 
-- -------------------------------------------------------------
-- Rate and Clocking Details
-- -------------------------------------------------------------
-- Design base rate: 1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: call_custom_exp_fixpt
-- Source Path: call_custom_exp_fixpt
-- Hierarchy Level: 0
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.call_custom_exp_fixpt_pkg.ALL;

ENTITY call_custom_exp_fixpt IS
  PORT( x                                 :   IN    std_logic_vector(13 DOWNTO 0);  -- sfix14_En9
        y                                 :   OUT   std_logic_vector(13 DOWNTO 0)  -- sfix14_En9
        );
END call_custom_exp_fixpt;


ARCHITECTURE rtl OF call_custom_exp_fixpt IS

  -- Constants
  CONSTANT nc                             : vector_of_unsigned14(0 TO 1023) := 
    (to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14),
     to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0000#, 14), to_unsigned(16#0001#, 14),
     to_unsigned(16#0001#, 14), to_unsigned(16#0001#, 14), to_unsigned(16#0001#, 14), to_unsigned(16#0001#, 14),
     to_unsigned(16#0001#, 14), to_unsigned(16#0001#, 14), to_unsigned(16#0001#, 14), to_unsigned(16#0001#, 14),
     to_unsigned(16#0001#, 14), to_unsigned(16#0001#, 14), to_unsigned(16#0001#, 14), to_unsigned(16#0001#, 14),
     to_unsigned(16#0001#, 14), to_unsigned(16#0001#, 14), to_unsigned(16#0001#, 14), to_unsigned(16#0001#, 14),
     to_unsigned(16#0001#, 14), to_unsigned(16#0001#, 14), to_unsigned(16#0001#, 14), to_unsigned(16#0001#, 14),
     to_unsigned(16#0001#, 14), to_unsigned(16#0001#, 14), to_unsigned(16#0001#, 14), to_unsigned(16#0001#, 14),
     to_unsigned(16#0001#, 14), to_unsigned(16#0001#, 14), to_unsigned(16#0001#, 14), to_unsigned(16#0001#, 14),
     to_unsigned(16#0001#, 14), to_unsigned(16#0001#, 14), to_unsigned(16#0001#, 14), to_unsigned(16#0001#, 14),
     to_unsigned(16#0001#, 14), to_unsigned(16#0001#, 14), to_unsigned(16#0001#, 14), to_unsigned(16#0002#, 14),
     to_unsigned(16#0002#, 14), to_unsigned(16#0002#, 14), to_unsigned(16#0002#, 14), to_unsigned(16#0002#, 14),
     to_unsigned(16#0002#, 14), to_unsigned(16#0002#, 14), to_unsigned(16#0002#, 14), to_unsigned(16#0002#, 14),
     to_unsigned(16#0002#, 14), to_unsigned(16#0002#, 14), to_unsigned(16#0002#, 14), to_unsigned(16#0002#, 14),
     to_unsigned(16#0002#, 14), to_unsigned(16#0002#, 14), to_unsigned(16#0002#, 14), to_unsigned(16#0002#, 14),
     to_unsigned(16#0002#, 14), to_unsigned(16#0002#, 14), to_unsigned(16#0002#, 14), to_unsigned(16#0002#, 14),
     to_unsigned(16#0003#, 14), to_unsigned(16#0003#, 14), to_unsigned(16#0003#, 14), to_unsigned(16#0003#, 14),
     to_unsigned(16#0003#, 14), to_unsigned(16#0003#, 14), to_unsigned(16#0003#, 14), to_unsigned(16#0003#, 14),
     to_unsigned(16#0003#, 14), to_unsigned(16#0003#, 14), to_unsigned(16#0003#, 14), to_unsigned(16#0003#, 14),
     to_unsigned(16#0003#, 14), to_unsigned(16#0003#, 14), to_unsigned(16#0004#, 14), to_unsigned(16#0004#, 14),
     to_unsigned(16#0004#, 14), to_unsigned(16#0004#, 14), to_unsigned(16#0004#, 14), to_unsigned(16#0004#, 14),
     to_unsigned(16#0004#, 14), to_unsigned(16#0004#, 14), to_unsigned(16#0004#, 14), to_unsigned(16#0004#, 14),
     to_unsigned(16#0004#, 14), to_unsigned(16#0004#, 14), to_unsigned(16#0005#, 14), to_unsigned(16#0005#, 14),
     to_unsigned(16#0005#, 14), to_unsigned(16#0005#, 14), to_unsigned(16#0005#, 14), to_unsigned(16#0005#, 14),
     to_unsigned(16#0005#, 14), to_unsigned(16#0005#, 14), to_unsigned(16#0005#, 14), to_unsigned(16#0006#, 14),
     to_unsigned(16#0006#, 14), to_unsigned(16#0006#, 14), to_unsigned(16#0006#, 14), to_unsigned(16#0006#, 14),
     to_unsigned(16#0006#, 14), to_unsigned(16#0006#, 14), to_unsigned(16#0006#, 14), to_unsigned(16#0007#, 14),
     to_unsigned(16#0007#, 14), to_unsigned(16#0007#, 14), to_unsigned(16#0007#, 14), to_unsigned(16#0007#, 14),
     to_unsigned(16#0007#, 14), to_unsigned(16#0007#, 14), to_unsigned(16#0008#, 14), to_unsigned(16#0008#, 14),
     to_unsigned(16#0008#, 14), to_unsigned(16#0008#, 14), to_unsigned(16#0008#, 14), to_unsigned(16#0008#, 14),
     to_unsigned(16#0009#, 14), to_unsigned(16#0009#, 14), to_unsigned(16#0009#, 14), to_unsigned(16#0009#, 14),
     to_unsigned(16#0009#, 14), to_unsigned(16#000A#, 14), to_unsigned(16#000A#, 14), to_unsigned(16#000A#, 14),
     to_unsigned(16#000A#, 14), to_unsigned(16#000A#, 14), to_unsigned(16#000B#, 14), to_unsigned(16#000B#, 14),
     to_unsigned(16#000B#, 14), to_unsigned(16#000B#, 14), to_unsigned(16#000B#, 14), to_unsigned(16#000C#, 14),
     to_unsigned(16#000C#, 14), to_unsigned(16#000C#, 14), to_unsigned(16#000C#, 14), to_unsigned(16#000D#, 14),
     to_unsigned(16#000D#, 14), to_unsigned(16#000D#, 14), to_unsigned(16#000E#, 14), to_unsigned(16#000E#, 14),
     to_unsigned(16#000E#, 14), to_unsigned(16#000E#, 14), to_unsigned(16#000F#, 14), to_unsigned(16#000F#, 14),
     to_unsigned(16#000F#, 14), to_unsigned(16#0010#, 14), to_unsigned(16#0010#, 14), to_unsigned(16#0010#, 14),
     to_unsigned(16#0011#, 14), to_unsigned(16#0011#, 14), to_unsigned(16#0011#, 14), to_unsigned(16#0012#, 14),
     to_unsigned(16#0012#, 14), to_unsigned(16#0012#, 14), to_unsigned(16#0013#, 14), to_unsigned(16#0013#, 14),
     to_unsigned(16#0013#, 14), to_unsigned(16#0014#, 14), to_unsigned(16#0014#, 14), to_unsigned(16#0015#, 14),
     to_unsigned(16#0015#, 14), to_unsigned(16#0015#, 14), to_unsigned(16#0016#, 14), to_unsigned(16#0016#, 14),
     to_unsigned(16#0017#, 14), to_unsigned(16#0017#, 14), to_unsigned(16#0018#, 14), to_unsigned(16#0018#, 14),
     to_unsigned(16#0019#, 14), to_unsigned(16#0019#, 14), to_unsigned(16#001A#, 14), to_unsigned(16#001A#, 14),
     to_unsigned(16#001B#, 14), to_unsigned(16#001B#, 14), to_unsigned(16#001C#, 14), to_unsigned(16#001C#, 14),
     to_unsigned(16#001D#, 14), to_unsigned(16#001E#, 14), to_unsigned(16#001E#, 14), to_unsigned(16#001F#, 14),
     to_unsigned(16#001F#, 14), to_unsigned(16#0020#, 14), to_unsigned(16#0021#, 14), to_unsigned(16#0021#, 14),
     to_unsigned(16#0022#, 14), to_unsigned(16#0023#, 14), to_unsigned(16#0023#, 14), to_unsigned(16#0024#, 14),
     to_unsigned(16#0025#, 14), to_unsigned(16#0025#, 14), to_unsigned(16#0026#, 14), to_unsigned(16#0027#, 14),
     to_unsigned(16#0028#, 14), to_unsigned(16#0029#, 14), to_unsigned(16#0029#, 14), to_unsigned(16#002A#, 14),
     to_unsigned(16#002B#, 14), to_unsigned(16#002C#, 14), to_unsigned(16#002D#, 14), to_unsigned(16#002E#, 14),
     to_unsigned(16#002F#, 14), to_unsigned(16#0030#, 14), to_unsigned(16#0030#, 14), to_unsigned(16#0031#, 14),
     to_unsigned(16#0032#, 14), to_unsigned(16#0033#, 14), to_unsigned(16#0034#, 14), to_unsigned(16#0036#, 14),
     to_unsigned(16#0037#, 14), to_unsigned(16#0038#, 14), to_unsigned(16#0039#, 14), to_unsigned(16#003A#, 14),
     to_unsigned(16#003B#, 14), to_unsigned(16#003C#, 14), to_unsigned(16#003D#, 14), to_unsigned(16#003F#, 14),
     to_unsigned(16#0040#, 14), to_unsigned(16#0041#, 14), to_unsigned(16#0042#, 14), to_unsigned(16#0044#, 14),
     to_unsigned(16#0045#, 14), to_unsigned(16#0047#, 14), to_unsigned(16#0048#, 14), to_unsigned(16#0049#, 14),
     to_unsigned(16#004B#, 14), to_unsigned(16#004C#, 14), to_unsigned(16#004E#, 14), to_unsigned(16#004F#, 14),
     to_unsigned(16#0051#, 14), to_unsigned(16#0053#, 14), to_unsigned(16#0054#, 14), to_unsigned(16#0056#, 14),
     to_unsigned(16#0058#, 14), to_unsigned(16#0059#, 14), to_unsigned(16#005B#, 14), to_unsigned(16#005D#, 14),
     to_unsigned(16#005F#, 14), to_unsigned(16#0061#, 14), to_unsigned(16#0063#, 14), to_unsigned(16#0064#, 14),
     to_unsigned(16#0066#, 14), to_unsigned(16#0068#, 14), to_unsigned(16#006B#, 14), to_unsigned(16#006D#, 14),
     to_unsigned(16#006F#, 14), to_unsigned(16#0071#, 14), to_unsigned(16#0073#, 14), to_unsigned(16#0076#, 14),
     to_unsigned(16#0078#, 14), to_unsigned(16#007A#, 14), to_unsigned(16#007D#, 14), to_unsigned(16#007F#, 14),
     to_unsigned(16#0082#, 14), to_unsigned(16#0084#, 14), to_unsigned(16#0087#, 14), to_unsigned(16#008A#, 14),
     to_unsigned(16#008C#, 14), to_unsigned(16#008F#, 14), to_unsigned(16#0092#, 14), to_unsigned(16#0095#, 14),
     to_unsigned(16#0098#, 14), to_unsigned(16#009B#, 14), to_unsigned(16#009E#, 14), to_unsigned(16#00A1#, 14),
     to_unsigned(16#00A4#, 14), to_unsigned(16#00A7#, 14), to_unsigned(16#00AB#, 14), to_unsigned(16#00AE#, 14),
     to_unsigned(16#00B1#, 14), to_unsigned(16#00B5#, 14), to_unsigned(16#00B9#, 14), to_unsigned(16#00BC#, 14),
     to_unsigned(16#00C0#, 14), to_unsigned(16#00C4#, 14), to_unsigned(16#00C8#, 14), to_unsigned(16#00CC#, 14),
     to_unsigned(16#00D0#, 14), to_unsigned(16#00D4#, 14), to_unsigned(16#00D8#, 14), to_unsigned(16#00DC#, 14),
     to_unsigned(16#00E1#, 14), to_unsigned(16#00E5#, 14), to_unsigned(16#00EA#, 14), to_unsigned(16#00EE#, 14),
     to_unsigned(16#00F3#, 14), to_unsigned(16#00F8#, 14), to_unsigned(16#00FD#, 14), to_unsigned(16#0102#, 14),
     to_unsigned(16#0107#, 14), to_unsigned(16#010C#, 14), to_unsigned(16#0111#, 14), to_unsigned(16#0117#, 14),
     to_unsigned(16#011C#, 14), to_unsigned(16#0122#, 14), to_unsigned(16#0127#, 14), to_unsigned(16#012D#, 14),
     to_unsigned(16#0133#, 14), to_unsigned(16#0139#, 14), to_unsigned(16#013F#, 14), to_unsigned(16#0146#, 14),
     to_unsigned(16#014C#, 14), to_unsigned(16#0153#, 14), to_unsigned(16#015A#, 14), to_unsigned(16#0160#, 14),
     to_unsigned(16#0167#, 14), to_unsigned(16#016E#, 14), to_unsigned(16#0176#, 14), to_unsigned(16#017D#, 14),
     to_unsigned(16#0185#, 14), to_unsigned(16#018C#, 14), to_unsigned(16#0194#, 14), to_unsigned(16#019C#, 14),
     to_unsigned(16#01A4#, 14), to_unsigned(16#01AD#, 14), to_unsigned(16#01B5#, 14), to_unsigned(16#01BE#, 14),
     to_unsigned(16#01C6#, 14), to_unsigned(16#01CF#, 14), to_unsigned(16#01D9#, 14), to_unsigned(16#01E2#, 14),
     to_unsigned(16#01EB#, 14), to_unsigned(16#01F5#, 14), to_unsigned(16#01FF#, 14), to_unsigned(16#0209#, 14),
     to_unsigned(16#0213#, 14), to_unsigned(16#021E#, 14), to_unsigned(16#0229#, 14), to_unsigned(16#0234#, 14),
     to_unsigned(16#023F#, 14), to_unsigned(16#024A#, 14), to_unsigned(16#0256#, 14), to_unsigned(16#0261#, 14),
     to_unsigned(16#026E#, 14), to_unsigned(16#027A#, 14), to_unsigned(16#0286#, 14), to_unsigned(16#0293#, 14),
     to_unsigned(16#02A0#, 14), to_unsigned(16#02AD#, 14), to_unsigned(16#02BB#, 14), to_unsigned(16#02C9#, 14),
     to_unsigned(16#02D7#, 14), to_unsigned(16#02E5#, 14), to_unsigned(16#02F4#, 14), to_unsigned(16#0303#, 14),
     to_unsigned(16#0312#, 14), to_unsigned(16#0321#, 14), to_unsigned(16#0331#, 14), to_unsigned(16#0341#, 14),
     to_unsigned(16#0352#, 14), to_unsigned(16#0363#, 14), to_unsigned(16#0374#, 14), to_unsigned(16#0385#, 14),
     to_unsigned(16#0397#, 14), to_unsigned(16#03A9#, 14), to_unsigned(16#03BC#, 14), to_unsigned(16#03CF#, 14),
     to_unsigned(16#03E2#, 14), to_unsigned(16#03F6#, 14), to_unsigned(16#040A#, 14), to_unsigned(16#041E#, 14),
     to_unsigned(16#0433#, 14), to_unsigned(16#0448#, 14), to_unsigned(16#045E#, 14), to_unsigned(16#0474#, 14),
     to_unsigned(16#048A#, 14), to_unsigned(16#04A1#, 14), to_unsigned(16#04B9#, 14), to_unsigned(16#04D1#, 14),
     to_unsigned(16#04E9#, 14), to_unsigned(16#0502#, 14), to_unsigned(16#051B#, 14), to_unsigned(16#0535#, 14),
     to_unsigned(16#054F#, 14), to_unsigned(16#056A#, 14), to_unsigned(16#0585#, 14), to_unsigned(16#05A1#, 14),
     to_unsigned(16#05BE#, 14), to_unsigned(16#05DB#, 14), to_unsigned(16#05F8#, 14), to_unsigned(16#0617#, 14),
     to_unsigned(16#0635#, 14), to_unsigned(16#0655#, 14), to_unsigned(16#0675#, 14), to_unsigned(16#0695#, 14),
     to_unsigned(16#06B7#, 14), to_unsigned(16#06D9#, 14), to_unsigned(16#06FB#, 14), to_unsigned(16#071E#, 14),
     to_unsigned(16#0742#, 14), to_unsigned(16#0767#, 14), to_unsigned(16#078D#, 14), to_unsigned(16#07B3#, 14),
     to_unsigned(16#07DA#, 14), to_unsigned(16#0801#, 14), to_unsigned(16#082A#, 14), to_unsigned(16#0853#, 14),
     to_unsigned(16#087D#, 14), to_unsigned(16#08A8#, 14), to_unsigned(16#08D4#, 14), to_unsigned(16#0900#, 14),
     to_unsigned(16#092E#, 14), to_unsigned(16#095C#, 14), to_unsigned(16#098C#, 14), to_unsigned(16#09BC#, 14),
     to_unsigned(16#09ED#, 14), to_unsigned(16#0A1F#, 14), to_unsigned(16#0A53#, 14), to_unsigned(16#0A87#, 14),
     to_unsigned(16#0ABC#, 14), to_unsigned(16#0AF2#, 14), to_unsigned(16#0B2A#, 14), to_unsigned(16#0B62#, 14),
     to_unsigned(16#0B9B#, 14), to_unsigned(16#0BD6#, 14), to_unsigned(16#0C12#, 14), to_unsigned(16#0C4F#, 14),
     to_unsigned(16#0C8D#, 14), to_unsigned(16#0CCD#, 14), to_unsigned(16#0D0D#, 14), to_unsigned(16#0D4F#, 14),
     to_unsigned(16#0D93#, 14), to_unsigned(16#0DD7#, 14), to_unsigned(16#0E1D#, 14), to_unsigned(16#0E65#, 14),
     to_unsigned(16#0EAD#, 14), to_unsigned(16#0EF7#, 14), to_unsigned(16#0F43#, 14), to_unsigned(16#0F90#, 14),
     to_unsigned(16#0FDF#, 14), to_unsigned(16#102F#, 14), to_unsigned(16#1081#, 14), to_unsigned(16#10D4#, 14),
     to_unsigned(16#1129#, 14), to_unsigned(16#1180#, 14), to_unsigned(16#11D9#, 14), to_unsigned(16#1233#, 14),
     to_unsigned(16#128F#, 14), to_unsigned(16#12ED#, 14), to_unsigned(16#134C#, 14), to_unsigned(16#13AE#, 14),
     to_unsigned(16#1411#, 14), to_unsigned(16#1477#, 14), to_unsigned(16#14DE#, 14), to_unsigned(16#1548#, 14),
     to_unsigned(16#15B3#, 14), to_unsigned(16#1621#, 14), to_unsigned(16#1691#, 14), to_unsigned(16#1703#, 14),
     to_unsigned(16#1777#, 14), to_unsigned(16#17EE#, 14), to_unsigned(16#1867#, 14), to_unsigned(16#18E2#, 14),
     to_unsigned(16#1960#, 14), to_unsigned(16#19E0#, 14), to_unsigned(16#1A63#, 14), to_unsigned(16#1AE8#, 14),
     to_unsigned(16#1B70#, 14), to_unsigned(16#1BFB#, 14), to_unsigned(16#1C88#, 14), to_unsigned(16#1D19#, 14),
     to_unsigned(16#1DAC#, 14), to_unsigned(16#1E42#, 14), to_unsigned(16#1EDB#, 14), to_unsigned(16#1F76#, 14),
     to_unsigned(16#2016#, 14), to_unsigned(16#20B8#, 14), to_unsigned(16#215D#, 14), to_unsigned(16#2206#, 14),
     to_unsigned(16#22B2#, 14), to_unsigned(16#2361#, 14), to_unsigned(16#2414#, 14), to_unsigned(16#24CA#, 14),
     to_unsigned(16#2584#, 14), to_unsigned(16#2642#, 14), to_unsigned(16#2703#, 14), to_unsigned(16#27C8#, 14),
     to_unsigned(16#2891#, 14), to_unsigned(16#295E#, 14), to_unsigned(16#2A30#, 14), to_unsigned(16#2B05#, 14));  -- ufix14 [1024]

  -- Signals
  SIGNAL x_signed                         : signed(13 DOWNTO 0);  -- sfix14_En9
  SIGNAL y_tmp                            : signed(13 DOWNTO 0);  -- sfix14_En9

BEGIN
  x_signed <= signed(x);

  call_custom_exp_fixpt_1_output : PROCESS (x_signed)
    VARIABLE LUT : vector_of_unsigned14(0 TO 1023);
    VARIABLE x_idx : signed(17 DOWNTO 0);
    VARIABLE idx_bot : signed(11 DOWNTO 0);
    VARIABLE tmp : signed(11 DOWNTO 0);
    VARIABLE x_idx_0 : signed(17 DOWNTO 0);
    VARIABLE idx_top : signed(11 DOWNTO 0);
    VARIABLE sub_cast : signed(14 DOWNTO 0);
    VARIABLE sub_temp : signed(14 DOWNTO 0);
    VARIABLE mul_temp : signed(29 DOWNTO 0);
    VARIABLE cast : signed(14 DOWNTO 0);
    VARIABLE sub_cast_0 : signed(18 DOWNTO 0);
    VARIABLE sub_cast_1 : signed(18 DOWNTO 0);
    VARIABLE sub_temp_0 : signed(18 DOWNTO 0);
    VARIABLE mul_temp_0 : signed(33 DOWNTO 0);
    VARIABLE add_cast : signed(32 DOWNTO 0);
    VARIABLE add_cast_0 : signed(33 DOWNTO 0);
    VARIABLE cast_0 : signed(14 DOWNTO 0);
    VARIABLE sub_cast_2 : signed(18 DOWNTO 0);
    VARIABLE sub_cast_3 : signed(18 DOWNTO 0);
    VARIABLE sub_temp_1 : signed(18 DOWNTO 0);
    VARIABLE mul_temp_1 : signed(33 DOWNTO 0);
    VARIABLE add_cast_1 : signed(32 DOWNTO 0);
    VARIABLE add_cast_2 : signed(33 DOWNTO 0);
    VARIABLE add_temp : signed(33 DOWNTO 0);
  BEGIN
    --HDL code generation from MATLAB function: call_custom_exp_fixpt
    LUT := nc;
    --%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    --                                                                          %
    --           Generated by MATLAB 9.5 and Fixed-Point Designer 6.2           %
    --                                                                          %
    --%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    --
    -- Copyright 2019 The MathWorks, Inc.
    -- calculate replacement_custom_fnc via lookup table between extents x = fi([-10,10]),
    -- interpolation degree  = 1, number of points = 1024
    sub_cast := resize(x_signed, 15);
    sub_temp := sub_cast - to_signed(-16#1400#, 15);
    mul_temp := sub_temp * to_signed(16#3326#, 15);
    x_idx := mul_temp(28 DOWNTO 11);
    idx_bot := x_idx(17 DOWNTO 6);
    IF idx_bot <= to_signed(16#000#, 12) THEN 
      tmp := to_signed(16#001#, 12);
    ELSE 
      tmp := idx_bot;
    END IF;
    x_idx_0 := x_idx + to_signed(16#00040#, 18);
    IF idx_bot >= to_signed(16#400#, 12) THEN 
      tmp := to_signed(16#3FF#, 12);
    END IF;
    idx_top := tmp + to_signed(16#001#, 12);
    cast := signed(resize(LUT(to_integer(resize(idx_top, 32) - 1)), 15));
    sub_cast_0 := resize(x_idx_0, 19);
    sub_cast_1 := resize(tmp & '0' & '0' & '0' & '0' & '0' & '0', 19);
    sub_temp_0 := sub_cast_0 - sub_cast_1;
    mul_temp_0 := cast * sub_temp_0;
    add_cast := mul_temp_0(32 DOWNTO 0);
    add_cast_0 := resize(add_cast, 34);
    cast_0 := signed(resize(LUT(to_integer(resize(tmp, 32) - 1)), 15));
    sub_cast_2 := resize(idx_top & '0' & '0' & '0' & '0' & '0' & '0', 19);
    sub_cast_3 := resize(x_idx_0, 19);
    sub_temp_1 := sub_cast_2 - sub_cast_3;
    mul_temp_1 := cast_0 * sub_temp_1;
    add_cast_1 := mul_temp_1(32 DOWNTO 0);
    add_cast_2 := resize(add_cast_1, 34);
    add_temp := add_cast_0 + add_cast_2;
    y_tmp <= add_temp(9 DOWNTO 0) & '0' & '0' & '0' & '0';
  END PROCESS call_custom_exp_fixpt_1_output;


  y <= std_logic_vector(y_tmp);

END rtl;

