/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 *
 * ldpcdec_wrapper_fixpt.c
 *
 * Code generation for function 'ldpcdec_wrapper_fixpt'
 *
 */

/* Include files */
#include "mwmathutil.h"
#include "rt_nonfinite.h"
#include "ldpcdec_fixpt_logger.h"
#include "ldpcdec_wrapper_fixpt.h"
#include "ldpcdec_fixpt.h"

/* Variable Definitions */
static emlrtRSInfo emlrtRSI = { 10,    /* lineNo */
  "ldpcdec_wrapper_fixpt",             /* fcnName */
  "/home/sky/Documents/MATLAB/Low_density_parity_code/codegen/ldpcdec/fixpt/ldpcdec_wrapper_fixpt.m"/* pathName */
};

/* Function Definitions */
void ldpcdec_wrapper_fixpt(const emlrtStack *sp, const real_T r[7], real_T iter,
  real_T dec_out[7])
{
  int32_T i0;
  real_T d0;
  int8_T b_r[7];
  int16_T dec_out_out[7];
  int8_T i1;
  emlrtStack st;
  st.prev = sp;
  st.tls = sp->tls;

  /* %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% */
  /*                                                                           % */
  /*            Generated by MATLAB 9.5 and Fixed-Point Designer 6.2           % */
  /*                                                                           % */
  /* %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% */
  for (i0 = 0; i0 < 7; i0++) {
    d0 = muDoubleScalarFloor(r[i0]);
    if (muDoubleScalarIsNaN(d0) || muDoubleScalarIsInf(d0)) {
      d0 = 0.0;
    } else {
      d0 = muDoubleScalarRem(d0, 4.0);
    }

    i1 = (int8_T)d0;
    if ((i1 & 2) != 0) {
      b_r[i0] = (int8_T)(i1 | -2);
    } else {
      b_r[i0] = (int8_T)(i1 & 1);
    }
  }

  d0 = muDoubleScalarFloor(iter);
  if (muDoubleScalarIsNaN(d0) || muDoubleScalarIsInf(d0)) {
    d0 = 0.0;
  } else {
    d0 = muDoubleScalarRem(d0, 1024.0);
  }

  st.site = &emlrtRSI;
  ldpcdec_fixpt(&st, b_r, (uint16_T)((uint16_T)(int16_T)d0 & 1023), dec_out_out);
  for (i0 = 0; i0 < 7; i0++) {
    dec_out[i0] = (real_T)dec_out_out[i0] * 0.5;
  }
}

/* End of code generation (ldpcdec_wrapper_fixpt.c) */
